modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "blubbysmodofdoom"
version = "${version}"
displayName = "Blubbys Mod Of Doom"
authors = ""
description = '''
'''
#logoFile = ""
[[dependencies.blubbysmodofdoom]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blubbysmodofdoom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blubbysmodofdoom]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
